return table.freeze({
	AutoTrain = "AutoTrain",
	Store = "Store",
	Coach = "Coach",
	Travel = "Travel",
	Rebirth = "Rebirth",
	Friends = "Friends",
	Inventory = "Inventory",
	AllRewards = "AllRewards",
	Settings = "Settings",
	Rewards = "Rewards",
	DailyRewards = "DailyRewards",
	Spins = "Spins",
	Season = "Season",
	GoldPets = "GoldPets",
	StarterPack = "StarterPack",
	ExclusivePack = "ExclusivePack",
	RainbowPets = "RainbowPets",
	UpdateLog = "UpdateLog",
	OfflineFarm = "OfflineFarm",
	OfflineNotification = "OfflineNotification",
	Characters = "Characters",
	Trails = "Trails",
	Rejoin = "Rejoin",
	TradeRequest = "TradeRequest",
	TradeList = "TradeList",
	Trade = "Trade",
})
