return table.freeze({
	["Onboarding"] = {
		First_Auto_On_Join = true,

		[1] = "Join the game",
		[2] = "Completed Kick Tutorial",
		[3] = "Completed 120 Power Training",
		[4] = "Completed Buy Coach",
		[5] = "Completed 150 Power Training",
		[6] = "Completed 50 Wins Challenge",
		[7] = "Completed Buy Player",
		[8] = "Completed Pet Hatching",
		[9] = "Unlocked New Zone (Tutorial End)",
	},

	["Progress"] = {
		[1] = {
			Tab_Name = "Progression",
			First_Auto_On_Join = true,

			[1] = "Join the game",
			[2] = "Unlocked second area",
			[3] = "Unlocked third area",
			[4] = "Unlocked fourth area",
			[5] = "Unlocked fifth area",
			[6] = "Unlocked sixth area",
			[7] = "Unlocked seventh area",
			[8] = "Unlocked eighth area",
			[9] = "Unlocked ninth area",
			[10] = "Unlocked tenth area",
			[11] = "Unlocked eleventh area",
			[12] = "Unlocked twelfth area",
			[13] = "Unlocked thirteenth area",
			[14] = "Unlocked fourteenth area",
		},
	},

	["Economy"] = {
		In_Game = {
			Money2 = 0,
			Wins = 0,
			Rebirth = 0,
		},

		Robux = {
			["Trail - Buy All"] = "Product",
			["Trail - Premium"] = "Product",
			["Trail - Skip 1"] = "Product",
			["Character - Rionel Messy"] = "Product",
			["Character - Ronaldinyo"] = "Product",
			["Character - Kristiano Ronalde"] = "Product",
			["Coach - Jos Morningho"] = "Product",
			["Coach - Saar Alex Ferguyon"] = "Product",
			["Body - Alien"] = "Product",
			["Body - Lava"] = "Product",
			["Body - Robot"] = "Product",
			["Body - GiftWrapper"] = "Product",
			["Boost Bundle"] = "Product",
			["Brainrot Pass - Plus"] = "Product",
			["Brainrot Pass - Regular"] = "Product",
			["Christmas Bundle"] = "Product",
			["Daily Rewards - Skip All"] = "Product",
			["Daily Rewards - Skip 1"] = "Product",
			["Demonic Paon"] = "Product",
			["Doctor Crow"] = "Product",
			["Golden Ram"] = "Product",
			["Lunar Moth"] = "Product",
			["Rebirth - Skip 1"] = "Product",
			["Rebirth - Skip 5"] = "Product",
			["Season Pass - Skip 1"] = "Product",
			["Season Pass - Skip All"] = "Product",
			["Sun Lion"] = "Product",
			["Time Rewards - Buy 2"] = "Product",
			["Time Rewards - Buy All"] = "Product",
			["White Tiger"] = "Product",
			["Wins Pack - Big"] = "Product",
			["Wins Pack - Huge"] = "Product",
			["Wins Pack - Regular"] = "Product",
			["Wins Pack - Small"] = "Product",
			["Exclusive Pack - Tier 1"] = "Product",
			["Exclusive Pack - Tier 2"] = "Product",
			["Exclusive Pack - Tier 3"] = "Product",
			["Exclusive Pack - Tier 4"] = "Product",
			["Exclusive Pack - Tier 5"] = "Product",
			["x1 Dominus Egg"] = "Product",
			["x1 Dragon Bat Egg"] = "Product",
			["x1 Free Pet"] = "Product",
			["x1 Giga Chad Egg"] = "Product",
			["x1 Premium Spins"] = "Product",
			["x1 Super Heroes Egg"] = "Product",
			["x1 Military Egg"] = "Product",
			["x1 Ball Egg"] = "Product",
			["x1 Christmas Egg"] = "Product",
			["x1 Monster Egg"] = "Product",
			["x2 Power Boost"] = "Product",
			["x2 Wins Boost"] = "Product",
			["x3 Dominus Egg"] = "Product",
			["x3 Dragon Bat Egg"] = "Product",
			["x3 Free Pet"] = "Product",
			["x3 Giga Chad Egg"] = "Product",
			["x3 Super Heroes Egg"] = "Product",
			["x3 Military Egg"] = "Product",
			["x3 Ball Egg"] = "Product",
			["x3 Monster Egg"] = "Product",
			["x3 Christmas Egg"] = "Product",
			["x8 Dominus Egg"] = "Product",
			["x8 Dragon Bat Egg"] = "Product",
			["x8 Giga Chad Egg"] = "Product",
			["x8 Super Heroes Egg"] = "Product",
			["x8 Military Egg"] = "Product",
			["x8 Ball Egg"] = "Product",
			["x8 Monster Egg"] = "Product",
			["x8 Christmas Egg"] = "Product",
			["x10 Free Pet"] = "Product",
			["x10 Free Spins"] = "Product",
			["x10 Premium Spins"] = "Product",
			["x30 Free Spins"] = "Product",
			["+2 Pet Equip"] = "GamePasses",
			["+4 Pet Equip"] = "GamePasses",
			["+7 Pet Equip"] = "GamePasses",
			["+25 Pet Storage"] = "GamePasses",
			["+50 Pet Storage"] = "GamePasses",
			["Lucky"] = "GamePasses",
			["x8 Hatch"] = "GamePasses",
			["Super Lucky"] = "GamePasses",
			["Teleport"] = "GamePasses",
			["x3 Hatch"] = "GamePasses",
			["VIP"] = "GamePasses",
			["x2 Power"] = "GamePasses",
			["x2 Rebirths"] = "GamePasses",
			["x2 Wins"] = "GamePasses",
			["Starter Pack"] = "Packs",
			["Pro Pack"] = "Packs",
			["Master Pack"] = "Packs",
		},
	},
})
